[project]
name = "rubikscross"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy<2",
    "opencv-python>=4.10.0.84",
    "pygame>=2.6.1",
]
